/*
 Project: dbx-capture
 File: DebugFrame.java (com.dividebyxero.dbxcapture.gui)
 Author: Alex Kersten
 */

/*
 * DebugFrame.java
 *
 * Created on Jun 3, 2013, 12:40:20 AM
 */
package com.dividebyxero.dbxcapture.gui;

import com.dividebyxero.dbxcapture.DBXCRuntime;
import com.dividebyxero.dbxcapture.jni.DBXCNativeInterface;
import javax.imageio.ImageIO;

/**
 *
 * @author Alex Kersten
 */
@SuppressWarnings("serial")
public class DebugFrame extends javax.swing.JFrame {

    private DBXCRuntime context;

    /**
     * Creates new form DebugFrame
     */
    public DebugFrame(DBXCRuntime context) {
        if (context == null) {
            return;
        }

        this.context = context;

        initComponents();
        try {
            setIconImage(ImageIO.read(
                    this.getClass().getResource("icon16.png")));
        } catch (Exception e) {
            System.err.println("Can't load frame icon.");
        }

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debugLabel = new javax.swing.JLabel();
        dumpBitmapButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        alertTextField = new javax.swing.JTextField();
        lockButton = new javax.swing.JButton();
        keycodeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DBXCapture - Debug");
        setResizable(false);

        debugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dividebyxero/dbxcapture/gui/icon128.png"))); // NOI18N
        debugLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        dumpBitmapButton.setText("Dump screen to bitmap in working directory");
        dumpBitmapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dumpBitmapButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Show test alert:");

        alertTextField.setText("Alert text");

        lockButton.setText("Lock until keycode:");
        lockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockButtonActionPerformed(evt);
            }
        });

        keycodeTextField.setText("65");
        keycodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keycodeTextFieldActionPerformed(evt);
            }
        });
        keycodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keycodeTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dumpBitmapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(debugLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alertTextField)
                            .addComponent(keycodeTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(debugLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dumpBitmapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(alertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lockButton)
                    .addComponent(keycodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dumpBitmapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dumpBitmapButtonActionPerformed
        DBXCNativeInterface.debugDumpBuffer();
    }//GEN-LAST:event_dumpBitmapButtonActionPerformed

    private void keycodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keycodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keycodeTextFieldActionPerformed

    private void keycodeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keycodeTextFieldKeyPressed
        keycodeTextField.setText(evt.getKeyCode() + "");
    }//GEN-LAST:event_keycodeTextFieldKeyPressed

    private void lockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockButtonActionPerformed
        try {
            DBXCNativeInterface.blockUntilKeypress(Integer.parseInt(keycodeTextField.getText()));
        } catch (NumberFormatException nfe) {
        }
    }//GEN-LAST:event_lockButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alertTextField;
    private javax.swing.JLabel debugLabel;
    private javax.swing.JButton dumpBitmapButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField keycodeTextField;
    private javax.swing.JButton lockButton;
    // End of variables declaration//GEN-END:variables

}
