/*
 Project: dbxcapture
 File: SettingsFrame.java (com.dividebyxero.dbxcapture.gui)
 Author: Alex Kersten
 */

/*
 * SettingsFrame.java
 *
 * Created on Jun 1, 2013, 11:16:55 AM
 */
package com.dividebyxero.dbxcapture.gui;

import com.dividebyxero.dbxcapture.DBXCRuntime;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Frame for modifying configuration of DBXCapture. Create it once at the
 * program startup and then hide it... Save the reference. Or don't, doesn't
 * really matter, it's just the better way.
 *
 * @author Alex Kersten
 */
@SuppressWarnings("serial")
public class SettingsFrame extends javax.swing.JFrame {

    private DBXCRuntime context;

    /**
     * Creates new form SettingsFrame. Only create after context.getSettings()
     * is accessible and loaded.
     *
     * Any state that needs to be read from the settings in the runtime context
     * is done here (i.e. looks for which scripts are active and populates the
     * dropdown menu with those, sets it to the right one based on current
     * index, etc.)
     */
    public SettingsFrame(DBXCRuntime context) {
        if (context == null) {
            JOptionPane.showMessageDialog(null, "No context for SettingsFrame!",
                                          "DBXCapture - Warning",
                                          JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.context = context;

        initComponents();
        try {
            setIconImage(ImageIO.read(new File("icon16.png")));
        } catch (Exception e) {
            System.err.println("Can't load frame icon.");
        }

        this.setLocationRelativeTo(null);

        updateButton.setVisible(false);
        setupFromLoadedSettings();
    }

    /**
     * Internal method for populating fields based on loaded settings read from
     * the runtime context.
     */
    @SuppressWarnings("unchecked")
    private void setupFromLoadedSettings() {

        //Populate fields based on current settings.
        confirmExitCheckBox.setSelected(context.getSettings().
                getSetting("bConfirmExit").equalsIgnoreCase("true"));

        contentDirectoryTextField.setText(context.getSettings().
                getSetting("sContentDirectory"));

        //Create model for script dropdown and set its index to the proper one.
        DefaultComboBoxModel<String> newModel = new DefaultComboBoxModel<>();

        for (int i = 0; i < context.getPostProcessScripts().length; i++) {
            newModel.addElement(context.getPostProcessScripts()[i]);
        }

        currentScriptComboBox.setModel(newModel);

        //We already know this index is within range - it was checked when the
        //settings were loaded.
        currentScriptComboBox.setSelectedIndex(
                Integer.parseInt(
                context.getSettings().getSetting("iUploadScript")));

        localmodeCheckBox.setSelected(context.getSettings().
                getSetting("bLocalMode").equalsIgnoreCase("true"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTabbedPane = new javax.swing.JTabbedPane();
        dbxcSettingsPanel = new javax.swing.JPanel();
        generalSettingsPanel = new javax.swing.JPanel();
        confirmExitCheckBox = new javax.swing.JCheckBox();
        contentDirectoryPanel = new javax.swing.JPanel();
        contentDirectoryTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        scriptsSettingsPanel = new javax.swing.JPanel();
        scriptinfo1Label = new javax.swing.JLabel();
        scriptinfo2Label = new javax.swing.JLabel();
        example1Label = new javax.swing.JLabel();
        example2Label = new javax.swing.JLabel();
        currentScriptPanel = new javax.swing.JPanel();
        currentScriptComboBox = new javax.swing.JComboBox();
        scriptinfo3Label = new javax.swing.JLabel();
        scriptVariablesPanel = new javax.swing.JPanel();
        imagepath1Label = new javax.swing.JLabel();
        imagepath2Label = new javax.swing.JLabel();
        localmodeCheckBox = new javax.swing.JCheckBox();
        localmodeLabel = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        dbxcaptureLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        githubButton = new javax.swing.JButton();
        dividebyxeroButton = new javax.swing.JButton();
        alexkerstenButton = new javax.swing.JButton();
        byLabel = new javax.swing.JLabel();
        githubLabel = new javax.swing.JLabel();
        dividebyxeroLabel = new javax.swing.JLabel();
        alexkerstenLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DBXCapture - Options");
        setResizable(false);

        generalSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        confirmExitCheckBox.setText("Confirm exit");

        javax.swing.GroupLayout generalSettingsPanelLayout = new javax.swing.GroupLayout(generalSettingsPanel);
        generalSettingsPanel.setLayout(generalSettingsPanelLayout);
        generalSettingsPanelLayout.setHorizontalGroup(
            generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmExitCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        generalSettingsPanelLayout.setVerticalGroup(
            generalSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmExitCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentDirectoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Content directory"));

        contentDirectoryTextField.setText("C:\\dbx\\DBXCapture\\tmp");

        javax.swing.GroupLayout contentDirectoryPanelLayout = new javax.swing.GroupLayout(contentDirectoryPanel);
        contentDirectoryPanel.setLayout(contentDirectoryPanelLayout);
        contentDirectoryPanelLayout.setHorizontalGroup(
            contentDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentDirectoryTextField)
                .addContainerGap())
        );
        contentDirectoryPanelLayout.setVerticalGroup(
            contentDirectoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentDirectoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        updateButton.setText("A new version of DBXCapture is available. Click to automatically install it.");

        javax.swing.GroupLayout dbxcSettingsPanelLayout = new javax.swing.GroupLayout(dbxcSettingsPanel);
        dbxcSettingsPanel.setLayout(dbxcSettingsPanelLayout);
        dbxcSettingsPanelLayout.setHorizontalGroup(
            dbxcSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbxcSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbxcSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentDirectoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        dbxcSettingsPanelLayout.setVerticalGroup(
            dbxcSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbxcSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentDirectoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("DBXC", dbxcSettingsPanel);

        scriptinfo1Label.setText("After capturing a screenshot and saving it to a file, dbxcapture passes the file path to a script for");

        scriptinfo2Label.setText("further processing. The default script uploads the screenshot to Imgur.");

        example1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        example1Label.setText("Example:");

        example2Label.setText("python uploadScrypt.py %imagepath%");

        currentScriptPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Current upload script"));

        currentScriptComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<selected script>" }));

        javax.swing.GroupLayout currentScriptPanelLayout = new javax.swing.GroupLayout(currentScriptPanel);
        currentScriptPanel.setLayout(currentScriptPanelLayout);
        currentScriptPanelLayout.setHorizontalGroup(
            currentScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentScriptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentScriptComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        currentScriptPanelLayout.setVerticalGroup(
            currentScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentScriptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        scriptinfo3Label.setText("These scripts are specified in scripts.cfg in the dbxcapture installation directory, one per line.");

        scriptVariablesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Script variables"));

        imagepath1Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imagepath1Label.setText("%imagepath%");

        imagepath2Label.setText("The absolute path to the most recent screenshot.");

        localmodeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        localmodeCheckBox.setText("%localmode%");

        localmodeLabel.setText("Save to desktop instead of upload.");

        javax.swing.GroupLayout scriptVariablesPanelLayout = new javax.swing.GroupLayout(scriptVariablesPanel);
        scriptVariablesPanel.setLayout(scriptVariablesPanelLayout);
        scriptVariablesPanelLayout.setHorizontalGroup(
            scriptVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptVariablesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scriptVariablesPanelLayout.createSequentialGroup()
                        .addComponent(imagepath1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagepath2Label))
                    .addGroup(scriptVariablesPanelLayout.createSequentialGroup()
                        .addComponent(localmodeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(localmodeLabel)))
                .addContainerGap())
        );
        scriptVariablesPanelLayout.setVerticalGroup(
            scriptVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptVariablesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagepath1Label)
                    .addComponent(imagepath2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scriptVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localmodeCheckBox)
                    .addComponent(localmodeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout scriptsSettingsPanelLayout = new javax.swing.GroupLayout(scriptsSettingsPanel);
        scriptsSettingsPanel.setLayout(scriptsSettingsPanelLayout);
        scriptsSettingsPanelLayout.setHorizontalGroup(
            scriptsSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptsSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptsSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scriptVariablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scriptinfo1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scriptinfo2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(scriptsSettingsPanelLayout.createSequentialGroup()
                        .addComponent(example1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(example2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(currentScriptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scriptinfo3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        scriptsSettingsPanelLayout.setVerticalGroup(
            scriptsSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptsSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scriptinfo1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scriptinfo2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentScriptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scriptinfo3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scriptsSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(example1Label)
                    .addComponent(example2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scriptVariablesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("Scripts", scriptsSettingsPanel);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dividebyxero/dbxcapture/gui/icon128.png"))); // NOI18N

        dbxcaptureLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dbxcaptureLabel.setText("DBXCapture");

        versionLabel.setText("<version>");

        authorLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        authorLabel.setText("Alex Kersten");

        githubButton.setText("GitHub Page");

        dividebyxeroButton.setText("dividebyxero.com");

        alexkerstenButton.setText("alexkersten.com");
        alexkerstenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alexkerstenButtonActionPerformed(evt);
            }
        });

        byLabel.setText("by");

        githubLabel.setText("Source code and revision history");

        dividebyxeroLabel.setText("Blog and DBXCapture project page");

        alexkerstenLabel.setText("Information about me and other projects");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel)
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(dbxcaptureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(byLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(githubButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alexkerstenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dividebyxeroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(githubLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dividebyxeroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alexkerstenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dbxcaptureLabel)
                            .addComponent(authorLabel)
                            .addComponent(byLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(githubButton)
                            .addComponent(githubLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dividebyxeroButton)
                            .addComponent(dividebyxeroLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alexkerstenButton)
                            .addComponent(alexkerstenLabel)))
                    .addComponent(iconLabel))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("About", aboutPanel);

        cancelButton.setText("Cancel");

        applyButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        applyButton.setText("Apply Changes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(settingsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(settingsTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(applyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alexkerstenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alexkerstenButtonActionPerformed
        //  
    }//GEN-LAST:event_alexkerstenButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton alexkerstenButton;
    private javax.swing.JLabel alexkerstenLabel;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel byLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox confirmExitCheckBox;
    private javax.swing.JPanel contentDirectoryPanel;
    private javax.swing.JTextField contentDirectoryTextField;
    private javax.swing.JComboBox currentScriptComboBox;
    private javax.swing.JPanel currentScriptPanel;
    private javax.swing.JPanel dbxcSettingsPanel;
    private javax.swing.JLabel dbxcaptureLabel;
    private javax.swing.JButton dividebyxeroButton;
    private javax.swing.JLabel dividebyxeroLabel;
    private javax.swing.JLabel example1Label;
    private javax.swing.JLabel example2Label;
    private javax.swing.JPanel generalSettingsPanel;
    private javax.swing.JButton githubButton;
    private javax.swing.JLabel githubLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel imagepath1Label;
    private javax.swing.JLabel imagepath2Label;
    private javax.swing.JCheckBox localmodeCheckBox;
    private javax.swing.JLabel localmodeLabel;
    private javax.swing.JPanel scriptVariablesPanel;
    private javax.swing.JLabel scriptinfo1Label;
    private javax.swing.JLabel scriptinfo2Label;
    private javax.swing.JLabel scriptinfo3Label;
    private javax.swing.JPanel scriptsSettingsPanel;
    private javax.swing.JTabbedPane settingsTabbedPane;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

}
